version: "3"

services:
  protoc-all:
    image: namely/protoc-all:latest
    command:
      -d ../api/
      -o ../api/
      -i https://github.com/googleapis/googleapis
      -l go
      --with-gateway
    volumes:
      - ./:/defs
